### ISSUE TITLE
Feature Proposal

### ISSUE THREAD

**Issue by erdahuja** [andreasonny83/unique-names-generator#19]
This use case arose in my implementation while i was using the package in a project.
Right now, dictionaries are not being used randomly, for example: if length is 2, and dictionaries are 3 (dic1, dic2, dic3). The package always used first 2 instead of picking any two randomly.

Here's i got around this,

```
      const customDictionary = [[colors, animals], [adjectives, animals]]
      const whichDictionary = Math.floor(Math.random() * 2);// 0 or 1, chose a combination, this could be generated randomly upto length and those many dictionaries can be chosen and used.
        uniquename: uniqueNamesGenerator({
          dictionaries: customDictionary[whichDictionary],
          length: 2,
          separator: "",
        });
```

**Comment by andreasonny83** [comment]
Hi @erdahuja .
This behaviour is actually intentional. If you have 3 dictionaries, let's say: adjectives, colors and animals, you might want to always generate random names maintaining this order.
I can, however, see a use case where you want to just generate random names not caring about the dictionary to use. I can try to add an extra flag `useAllDictionary` that, when set to `true`, it will generate the name using all the dictionaries available.
Let me know if this will help you with your problem

**Comment by erdahuja** [comment]
Yes, That'd be great. Can i do this?

**Comment by andreasonny83** [comment]
Absolutely. PR are always welcome. I'll be happy to review and merge that once ready. Thanks

**Comment by andreasonny83** [comment]
@erdahuja are you going to create a PR for this or should I implement the new flag?

**Comment by erdahuja** [comment]
Sorry for the delay, i will do it. Give me 72 hours please :)

**Comment by andreasonny83** [comment]
Any update on this @erdahuja ?

**Comment by erdahuja** [comment]
It's Complete! @andreasonny83 What are you awaiting me on?
