### ISSUE TITLE
seeding the generator

### ISSUE THREAD

**Issue by chase-moskal** [andreasonny83/unique-names-generator#23]
hello friend, this looks like a wonderful library!

i was thinking i'd like to generate random nicknames as defaults for my users

i'd like to seed the name generator with the email address of the user -- so that if re-authentication ever occurred, the user would receive the same pseudorandomly generated name

i wonder how we could implement this?

cheers!

&nbsp; 👋 chase

**Comment by andreasonny83** [comment]
Hi @chase-moskal 
Thanks for the feedback first of all.
The library is supposed to just generate random names. I believe, if you want to seed the result matching a given input, you should manually store a table of key value pairs where you store your email address to the corresponding generated name.
What I mean is to store an extra value in your database where you store the user information. You can add an extra `friendlyName` column in there and, if empty then generate a unique name, otherwise just fetch the value from the database.
However, I can think about adding a seed name generator feature in the future to avoid doing this manually

**Comment by chase-moskal** [comment]
we want microservices to be as stateless as possible, and so a seeded pseudorandom name would be ideal -- we certainly don't want to implement and maintain a special database table and associated logic to achieve this

let me know if you begin work on this feature, because i might like to implement it and send a pull request some time in the future, i'll let you know if i do

it looks like implementing this should be fairly simple, looking at the [source](https://github.com/andreasonny83/unique-names-generator/blob/master/src/unique-names-generator.constructor.ts#L50)

cheers!

&nbsp; :wave: chase

**Comment by andreasonny83** [comment]
@all-contributors please add @chase-moskal  for ideas

**Comment by andreasonny83** [comment]
Fixed by #33

**Comment by andreasonny83** [comment]
@all-contributors please add @chase-moskal for ideas
